


# CONFIGURACIÓN DE BASE DE DATOS (MARIADB)
spring.datasource.url=jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_NAME}?createDatabaseIfNotExist=true&sslMode=trust
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# ESTRATEGIA DE GENERACIÓN DE TABLAS
spring.sql.init.mode=never
spring.jpa.hibernate.ddl-auto=update

# PROPIEDADES JPA / HIBERNATE 7
# (Se usa database-platform en lugar de dialect directo para mejor compatibilidad con Spring Boot)
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false

# OPTIMIZACIÓN DE LOGS (Silencia la advertencia de MultiTenantConnectionProvider)
logging.level.org.springframework.orm.jpa.hibernate=INFO


# VARIABLES DE ENTORNO DE AWS
aws.access.key.id=${AWS_ACCESS_KEY_ID}
aws.secret.access.key=${AWS_SECRET_ACCESS_KEY}
aws.session.token=${AWS_SESSION_TOKEN}
aws.region=${AWS_REGION}
security.jwt.secret=${JWT_SECRET}



