spring.application.name=usuarios

# Server Configuration
server.port=8083

# MariaDB Database Configuration
spring.datasource.url=jdbc:mariadb://localhost:3306/usuarios_db
spring.datasource.driverClassName=org.mariadb.jdbc.Driver
spring.datasource.username=usuario_test
spring.datasource.password=1234

# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Secret key
security.jwt.secret=${JWT_SECRET}